# permissions for end users to view anandazureavms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: anandazureavm-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vmstate-operator
    app.kubernetes.io/part-of: vmstate-operator
    app.kubernetes.io/managed-by: kustomize
  name: anandazureavm-viewer-role
rules:
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - anandazureavms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - anandazureavms/status
  verbs:
  - get
